theme: jekyll-theme-cayman
title: [toguma]
description: [日記]
logo: asset/icon.jpg
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]